# Generated by Django 2.2.2 on 2019-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(help_text='Book Id', primary_key=True, serialize=False),
        ),
    ]
