# Generated by Django 2.2.2 on 2019-06-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190620_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Student Name', max_length=100, null=True)),
                ('usn', models.CharField(help_text='Student USN', max_length=10, null=True)),
                ('borrow_date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('book_borrowed', models.ForeignKey(help_text='Book Bought', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Book')),
            ],
        ),
    ]
